# Generated by Django 3.0.1 on 2020-01-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False, verbose_name='employee_id')),
                ('name', models.TextField(max_length=100, verbose_name='employee_name')),
                ('address', models.TextField(max_length=200, verbose_name='employee_address')),
                ('phone', models.TextField(max_length=10, verbose_name='employee_phone')),
                ('department', models.TextField(max_length=100, verbose_name='employee_department')),
                ('isadmin', models.BooleanField(max_length=1, verbose_name='admin/user')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('punchid', models.AutoField(primary_key=True, serialize=False)),
                ('punchin', models.TimeField()),
                ('punchout', models.TimeField()),
                ('date', models.DateField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentbook.Employee')),
            ],
            options={
                'db_table': 'punch',
            },
        ),
    ]
